elite_journals = [
    "Academy of Management Journal",
    "Academy of Management Review",
    "Accounting Organizations and Society",
    "Accounting Review (The Accounting Review)",
    "Administrative Science Quarterly",
    "American Business Law Journal",
    "Annals of Tourism Research",
    "Contemporary Accounting Research",
    "Information Systems Research",
    "International Journal of Hospitality Management",
    "Journal of Accounting and Economics",
    "Journal of Accounting Research",
    "Journal of Applied Psychology",
    "Journal of Consumer Research",
    "Journal of Finance",
    "Journal of Financial and Quantitative Analysis",
    "Journal of Financial Economics",
    "Journal of Hospitality & Tourism Research",
    "Journal of International Business Studies",
    "Journal of Management Information Systems (Information Systems Journal)",
    "Journal of Marketing",
    "Journal of Marketing Research",
    "Journal of Operations Management",
    "Management Science",
    "Marketing Science",
    "MIS Quarterly",
    "Operations Research",
    "Organization Science",
    "Production and Operations Management",
    "Review of Financial Studies",
    "Strategic Management Journal",
    "Tourism Management",
    "Journal of Business Venturing",
    "Journal of Management",
    "Manufacturing and Service Operations MGT",
    "Journal of Travel Research"
]
